apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: actuator-sample
spec:
  selector:
    matchLabels:
      type: api
      service: actuator-sample
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        type: api
        service: actuator-sample
    spec:
      containers:
      - name: actuator-sample
        image: quay.io/timcurless/actuator-sample:<tag>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-server

---

apiVersion: v1
kind: Service
metadata:
  name: actuator-sample
spec:
  ports:
  - port: 80
    targetPort: http-server
  selector:
    type: api
    service: actuator-sample
  type: LoadBalancer
